[package]
name = "santa-translator"
version = "0.1.0"
edition = "2021"

[[bin]]
edition = "2021"
name = "santa_translator"
path = "src/main.rs"

[dependencies]
bimap = "0.6.3"
clap = { version = "4.5.23", features = ["derive"] }
lazy_static = "1.5.0"
