name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: cargo test --verbose

